// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3q4W5Mh4e6esavA0kvC8veEbbDMaCTz4',
    appId: '1:455502033179:web:889c667f3caa35881ee3be',
    messagingSenderId: '455502033179',
    projectId: 'hospital-ad9de',
    authDomain: 'hospital-ad9de.firebaseapp.com',
    storageBucket: 'hospital-ad9de.appspot.com',
    measurementId: 'G-XDQ092DT8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1HmLNY1N9QQvFYWkwod_pyis1wRTgpU',
    appId: '1:455502033179:android:6b01e63003e991421ee3be',
    messagingSenderId: '455502033179',
    projectId: 'hospital-ad9de',
    storageBucket: 'hospital-ad9de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWS4J6e-0rdhsuPv5UKlzIC1_mP2ADQfM',
    appId: '1:455502033179:ios:7fc4c8bea25147bc1ee3be',
    messagingSenderId: '455502033179',
    projectId: 'hospital-ad9de',
    storageBucket: 'hospital-ad9de.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWS4J6e-0rdhsuPv5UKlzIC1_mP2ADQfM',
    appId: '1:455502033179:ios:ca66632546198e2c1ee3be',
    messagingSenderId: '455502033179',
    projectId: 'hospital-ad9de',
    storageBucket: 'hospital-ad9de.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
